---
- name: Playbook for upgrading the RPis
  hosts: rpi0
  user: pi
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Update apt package cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=86400
  - name: Upgrade apt packages
    apt: upgrade=dist force_apt_get=yes  
  - name: Check if a reboot is needed on all servers
    register: reboot_required_file
    stat: path=/var/run/reboot-required get_md5=no
  - name: Reboot the PIs if kernel updated
    reboot:
      msg: "Reboot initiated by Ansible for kernel update"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: reboot_required_file.stat.exists
